[project]
name = "personal-site-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alex Bates", email = "alexbates.dev@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
personal-site-backend = "personal_site_backend.main:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
